export const ADD_RANDOM_CONTACT = 'ADD_RANDOM_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const SET_LIMIT = 'SET_LIMIT';
export const CLEAR_LIMIT = 'CLEAR_LIMIT';